version: '3.8'

services:
  chromakit-backend:
    image: ghcr.io/swiftcontrol/chromakit-backend:latest
    container_name: chromakit-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET:-images}
      - SUPABASE_DISABLED=${SUPABASE_DISABLED:-0}
      - SUPABASE_STORAGE_LOCAL_DIR=${SUPABASE_STORAGE_LOCAL_DIR:-.local_storage}
    volumes:
      # Persist local storage if SUPABASE_DISABLED=1
      - /var/lib/chromakit/storage:/app/.local_storage
      - /var/log/chromakit:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chromakit-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  nginx:
    image: nginx:alpine
    container_name: chromakit-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - chromakit-network
    depends_on:
      - chromakit-backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

networks:
  chromakit-network:
    driver: bridge