line-length = 120

[lint]
extend-select = ["E", "F", "I", "UP", "B", "SIM", "N", "C4"]
ignore = [
  # Allow prints in small scripts/tests
  "T201",
  # Allow FastAPI Depends() in function defaults - this is the standard FastAPI pattern
  "B008",
]

